-- Create a table for public "todos"
create table todos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text,
  is_completed boolean default false,
  created_at timestamptz default now()
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security
alter table todos
  enable row level security;

create policy "Allow logged-in users to insert a todo" for insert to todos with check (auth.uid() = user_id);
create policy "Allow logged-in users to view their own todos" for select to todos using (auth.uid() = user_id);
create policy "Allow logged-in users to update their own todos" for update to todos with check (auth.uid() = user_id);
create policy "Allow logged-in users to delete their own todos" for delete to todos using (auth.uid() = user_id);
